package com.aml.system.model;

import com.aml.system.model.enums.AlertSeverity;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Compliance Alert Entity.
 * Represents an AML suspicious detection generated by rule evaluation.
 *
 * Persisted using JPA for operational compliance review and Case escalation.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "aml_alerts", indexes = {
        @Index(name = "idx_alert_tenant_rule", columnList = "tenantId, ruleCode"),
        @Index(name = "idx_alert_customer", columnList = "customerId, createdAt"),
        @Index(name = "idx_alert_status", columnList = "tenantId, isReviewed")
})
public class Alert {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID alertId;

    @Column(nullable = false, length = 64)
    private String tenantId;

    @Column(nullable = false)
    private UUID transactionId;

    @Column(nullable = false, length = 128)
    private String customerId;

    @Column(nullable = false, length = 64)
    private String ruleCode;

    @Column(nullable = false, length = 255)
    private String ruleName;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 32)
    private AlertSeverity severity;

    @Column(nullable = false, precision = 19, scale = 4)
    private BigDecimal triggeredAmount;

    @Column(columnDefinition = "TEXT")
    private String narrative;

    @Column(columnDefinition = "TEXT")
    private String detectionMetadataJson;

    @Builder.Default
    @Column(nullable = false)
    private Boolean isReviewed = false;

    @Column
    private UUID assignedCaseId;

    @Builder.Default
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt = LocalDateTime.now();
}
