# ====================================================================
# LOCAL DEVELOPER CREDENTIALS (Do NOT commit to Git)
# ====================================================================

spring.datasource.url=jdbc:postgresql://localhost:5432/aml_master
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5

# ====================================================================
# JWT SECURITY CONFIGURATION
# ====================================================================
# Expiration time in milliseconds (1 Hour = 3600000 ms)
jwt.expiration=3600000
# 256-bit Base64 encoded secret key (DO NOT commit prod keys to Git!)
jwt.secret=413F4428472B4B6250655368566D5970337336763979244226452948404D6351


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=notify71845@gmail.com
spring.mail.password=vmhtjobngseflsay
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

